# Generated by Django 2.0.2 on 2018-04-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditContents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('audit_type', models.CharField(choices=[('0', '数据变更'), ('1', '数据导出')], default='0', max_length=10, verbose_name='线上审核类型')),
                ('operate_type', models.CharField(choices=[('DDL', '数据库定义语言'), ('DML', '数据库操纵语言')], default='DML', max_length=5, verbose_name='操作类型: DDL or DML')),
                ('proposer', models.CharField(default='', max_length=30, verbose_name='申请人， 一般为开发或者产品，存储username')),
                ('verifier', models.CharField(default='', max_length=30, verbose_name='批准人，一般为项目经理或Leader， 存储username')),
                ('operator', models.CharField(default='', max_length=30, verbose_name='执行人，一般为DBA， 存储username')),
                ('email_cc', models.CharField(default='', max_length=1024, verbose_name='抄送人， 存储contact_id，以逗号分隔')),
                ('host', models.CharField(default='', max_length=30, verbose_name='操作数据库主机')),
                ('database', models.CharField(default='', max_length=80, verbose_name='操作数据库')),
                ('progress', models.CharField(choices=[('0', '待批准'), ('1', '未批准'), ('2', '已批准'), ('3', '处理中'), ('4', '已完成'), ('5', '已关闭')], default='0', max_length=10, verbose_name='任务进度')),
                ('verifier_time', models.DateTimeField(auto_now_add=True, verbose_name='审批时间')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='执行的时间')),
                ('close_user', models.CharField(default='', max_length=30, verbose_name='关闭记录的用户')),
                ('close_reason', models.CharField(default='', max_length=1024, verbose_name='关闭原因')),
                ('close_time', models.DateTimeField(auto_now_add=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审核内容',
                'verbose_name_plural': '审核内容',
                'db_table': 'auditsql_audit_contents',
            },
        ),
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('domain_name', models.CharField(default='', max_length=256, verbose_name='域名地址')),
            ],
            options={
                'verbose_name': '域名地址',
                'verbose_name_plural': '域名地址',
                'db_table': 'auditsql_domain_name',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='IncepMakeExecTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('uid', models.IntegerField(default=0, verbose_name='操作用户uid')),
                ('user', models.CharField(max_length=30, verbose_name='操作用户')),
                ('taskid', models.CharField(max_length=128, verbose_name='任务号')),
                ('related_id', models.IntegerField(default=0, verbose_name='关联AuditContents的主键id')),
                ('category', models.CharField(choices=[('0', '线下任务'), ('1', '线上任务')], default='0', max_length=2, verbose_name='任务分类')),
                ('dst_host', models.CharField(max_length=30, verbose_name='操作目标数据库主机')),
                ('dst_database', models.CharField(max_length=80, verbose_name='操作目标数据库')),
                ('sql_content', models.TextField(default='', verbose_name='执行的SQL')),
                ('type', models.CharField(choices=[('DDL', '数据库定义语言'), ('DML', '数据库操纵语言')], default='', max_length=5)),
                ('sqlsha1', models.CharField(default='', max_length=120, verbose_name='sqlsha1')),
                ('rollback_sqlsha1', models.CharField(default='', max_length=120, verbose_name='sqlsha1')),
                ('exec_status', models.CharField(choices=[('0', '未执行'), ('1', '已完成'), ('2', '处理中'), ('3', '回滚中'), ('4', '已回滚')], default='0', max_length=10, verbose_name='执行进度')),
                ('sequence', models.CharField(default='', max_length=1024, verbose_name='备份记录id，inception生成的sequence')),
                ('affected_row', models.IntegerField(default=0, verbose_name='预计影响行数')),
                ('backup_dbname', models.CharField(default='', max_length=1024, verbose_name='inception生成的备份的库名')),
                ('exec_log', models.TextField(default='', verbose_name='执行成功的记录')),
                ('make_time', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '生成Inception执行任务',
                'verbose_name_plural': '生成Inception执行任务',
                'db_table': 'auditsql_incep_tasks',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InceptionHostConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('user', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('host', models.CharField(max_length=32, verbose_name='ip地址')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('type', models.IntegerField(default=0, verbose_name='0:线下数据库，1:线上数据库')),
                ('is_enable', models.IntegerField(default=0, verbose_name='0:启用，1：禁用')),
                ('protection_user', models.TextField(default='root', verbose_name='被保护的数据库账号， 以逗号分隔')),
                ('comment', models.CharField(max_length=128, verbose_name='主机描述')),
            ],
            options={
                'verbose_name': '数据库连接账号',
                'verbose_name_plural': '数据库连接账号',
                'db_table': 'auditsql_inception_hostconfig',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InceptionHostConfigDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'inception主机分组',
                'verbose_name_plural': 'inception主机分组',
                'db_table': 'auditsql_inception_hostconfig_detail',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MonitorSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_schema', models.CharField(max_length=512)),
                ('table_name', models.CharField(max_length=512)),
                ('table_stru', models.TextField(default='')),
                ('md5_sum', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '监控表结构变更表',
                'verbose_name_plural': '监控表结构变更表',
                'db_table': 'auditsql_monitor_schema',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OlAuditContentsReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('reply_contents', models.TextField(default='', verbose_name='回复内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('reply', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project_manager.AuditContents')),
            ],
            options={
                'verbose_name': '线上审核回复表',
                'verbose_name_plural': '线上审核回复表',
                'db_table': 'auditsql_ol_audit_reply',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OlAuditDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('contents', models.TextField(default='', verbose_name='提交的内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.AuditContents', verbose_name='关联审核内容表id')),
            ],
            options={
                'verbose_name': '线上审核内容详情表',
                'verbose_name_plural': '线上审核内容详情表',
                'db_table': 'auditsql_ol_audit_detail',
            },
        ),
        migrations.CreateModel(
            name='OlDataExportDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('file_coding', models.CharField(default='', max_length=256, verbose_name='文件编码')),
                ('file_format', models.CharField(default='', max_length=256, verbose_name='文件格式')),
                ('file_name', models.CharField(default='', max_length=256, verbose_name='文件名')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小，单位B')),
                ('files', models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='文件上传的路径url')),
                ('encryption_key', models.CharField(default='', max_length=128, verbose_name='加密秘钥')),
                ('progress', models.CharField(choices=[('0', '未执行'), ('1', '导出中'), ('2', '已生成')], default='0', max_length=10, verbose_name='导出进度')),
                ('contents', models.TextField(default='', verbose_name='提交的内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.AuditContents', verbose_name='关联审核内容表id')),
            ],
            options={
                'verbose_name': '线上数据导出详情表',
                'verbose_name_plural': '线上数据导出详情表',
                'db_table': 'auditsql_ol_data_export_detail',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('remark', models.CharField(default='', max_length=30, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '线上操作备注',
                'verbose_name_plural': '线上操作备注',
                'db_table': 'auditsql_audit_remark',
                'default_permissions': (),
            },
        ),
    ]
