# Generated by Django 2.0.2 on 2018-04-19 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_manager', '0001_initial'),
        ('user_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='olauditcontentsreply',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inceptionhostconfigdetail',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.InceptionHostConfig'),
        ),
        migrations.AddField(
            model_name='inceptionhostconfigdetail',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.Groups'),
        ),
        migrations.AlterUniqueTogether(
            name='inceptionhostconfig',
            unique_together={('host',)},
        ),
        migrations.AddField(
            model_name='incepmakeexectask',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.Groups', verbose_name='项目组id'),
        ),
        migrations.AddField(
            model_name='auditcontents',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.Groups', verbose_name='关联项目组表id'),
        ),
        migrations.AlterUniqueTogether(
            name='auditcontents',
            unique_together={('title',)},
        ),
    ]
