# Generated by Django 2.0.2 on 2018-08-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_auto_20180815_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcontents',
            name='envi_desc',
            field=models.SmallIntegerField(default=0, verbose_name='环境：0：测试、1：staging、2：生产、3：线下其他环境'),
        ),
        migrations.AlterField(
            model_name='incepmakeexectask',
            name='envi_desc',
            field=models.SmallIntegerField(default=0, verbose_name='环境：0：测试、1：staging、2：生产、3：线下其他环境'),
        ),
    ]
