# Generated by Django 2.0.2 on 2018-04-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_auto_20180419_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olauditdetail',
            name='operate_type',
        ),
        migrations.AddField(
            model_name='auditcontents',
            name='operate_type',
            field=models.CharField(choices=[('DDL', '数据库定义语言'), ('DML', '数据库操纵语言')], default='', max_length=5, verbose_name='操作类型: DDL or DML'),
        ),
    ]
