# Generated by Django 2.0.2 on 2018-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0003_auto_20180419_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcontents',
            name='audit_type',
            field=models.CharField(choices=[('0', '数据变更'), ('1', '数据导出')], default='0', max_length=10, verbose_name='线上审核类型'),
        ),
        migrations.AlterField(
            model_name='auditcontents',
            name='operate_type',
            field=models.CharField(choices=[('DDL', '数据库定义语言'), ('DML', '数据库操纵语言')], default='DML', max_length=5, verbose_name='操作类型: DDL or DML'),
        ),
    ]
