# Generated by Django 2.0.2 on 2018-04-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0004_auto_20180420_1152'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exportfiles',
            table='sqlaudit_export_files',
        ),
    ]
