# Generated by Django 2.0.2 on 2018-04-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0005_auto_20180420_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
