# Generated by Django 2.0.2 on 2018-05-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0006_delete_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incepmakeexectask',
            name='rollback_sqlsha1',
        ),
        migrations.RemoveField(
            model_name='incepmakeexectask',
            name='sqlsha1',
        ),
        migrations.AddField(
            model_name='incepmakeexectask',
            name='task_id',
            field=models.CharField(default='', max_length=256, verbose_name='celery执行任务ID'),
        ),
    ]
