# Generated by Django 2.0.2 on 2018-05-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0007_auto_20180516_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='incepmakeexectask',
            name='sqlsha1',
            field=models.CharField(default='', max_length=120, verbose_name='sqlsha1'),
        ),
    ]
