# Generated by Django 2.0.2 on 2018-05-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0009_auto_20180516_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='incepmakeexectask',
            name='rollback_sqlsha1',
            field=models.CharField(default='', max_length=120, verbose_name='rollbackup sqlsha1'),
        ),
    ]
