# Generated by Django 2.0.2 on 2018-05-30 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0012_auto_20180523_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportfiles',
            name='export',
        ),
        migrations.RemoveField(
            model_name='oldataexportdetail',
            name='ol',
        ),
        migrations.RemoveField(
            model_name='auditcontents',
            name='audit_type',
        ),
        migrations.DeleteModel(
            name='ExportFiles',
        ),
        migrations.DeleteModel(
            name='OlDataExportDetail',
        ),
    ]
