# Generated by Django 2.0.2 on 2018-05-31 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0013_auto_20180530_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inceptionhostconfig',
            unique_together={('host', 'port')},
        ),
    ]
