# Generated by Django 2.0.2 on 2018-06-02 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0015_webhook'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inceptionhostconfig',
            unique_together={('is_enable', 'comment'), ('host', 'port')},
        ),
    ]
