# Generated by Django 2.1.7 on 2019-03-16 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('host', models.CharField(max_length=128, verbose_name='地址')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('character', models.CharField(choices=[('utf8', 'utf8'), ('utf8mb4', 'utf8mb4')], default='utf8', max_length=32, verbose_name='库表字符集')),
                ('type', models.SmallIntegerField(choices=[(0, 'SQL审核'), (1, 'SQL查询')], default=0, verbose_name='用途')),
                ('rsd_type', models.SmallIntegerField(choices=[(0, '非阿里云RDS'), (1, '阿里云RDS')], default=0, verbose_name='数据库的类型')),
                ('comment', models.CharField(max_length=128, null=True, verbose_name='主机描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'MySQL主机配置',
                'verbose_name_plural': 'MySQL主机配置',
                'db_table': 'auditsql_mysql_config',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MysqlSchemas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('schema', models.CharField(default='', max_length=64, verbose_name='库名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MysqlConfig', verbose_name='主机')),
            ],
            options={
                'verbose_name': 'MySQL库信息',
                'verbose_name_plural': 'MySQL库信息',
                'db_table': 'auditsql_mysql_schemas',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OnlineVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('username', models.CharField(default='', max_length=128, verbose_name='创建用户')),
                ('version', models.CharField(default='', max_length=128, verbose_name='版本号')),
                ('expire_time', models.DateTimeField(default='2000-11-01 01:01:01', verbose_name='截止上线日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '上线版本号',
                'verbose_name_plural': '上线版本号',
                'db_table': 'auditsql_online_version',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('title', models.CharField(max_length=100, verbose_name='工单标题')),
                ('description', models.CharField(default='', max_length=2048, verbose_name='工单需求描述')),
                ('remark', models.CharField(default='', max_length=128, verbose_name='工单备注')),
                ('sql_type', models.CharField(choices=[('DDL', 'DDL工单'), ('DML', 'DML工单'), ('OPS', '运维工单'), ('EXPORT', '数据导出工单')], default='DML', max_length=30, verbose_name='工单类型')),
                ('file_format', models.CharField(choices=[('xlsx', 'xlsx格式'), ('csv', 'csv格式')], default='xlsx', max_length=30, verbose_name='文件格式')),
                ('applicant', models.CharField(default='', max_length=30, verbose_name='工单申请人')),
                ('auditor', models.CharField(default='', max_length=4096, verbose_name='工单审核人')),
                ('reviewer', models.CharField(default='', max_length=4096, verbose_name='工单复核人')),
                ('email_cc', models.CharField(default='', max_length=4096, verbose_name='抄送联系人')),
                ('host', models.CharField(default='', max_length=128, verbose_name='主机')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('database', models.CharField(default='', max_length=30, verbose_name='库名')),
                ('progress', models.CharField(choices=[('0', '待批准'), ('1', '未批准'), ('2', '已批准'), ('3', '处理中'), ('4', '已完成'), ('5', '已关闭'), ('6', '已勾住'), ('7', '复核中'), ('8', '已复核')], default='0', max_length=30, verbose_name='任务进度')),
                ('task_version', models.CharField(default='', max_length=256, verbose_name='上线版本')),
                ('close_info', models.CharField(default='', max_length=1024, verbose_name='关闭记录的详情')),
                ('contents', models.TextField(default='', verbose_name='提交的工单内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工单记录',
                'verbose_name_plural': '工单记录',
                'db_table': 'auditsql_orders',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OrdersTasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('taskid', models.CharField(max_length=128, verbose_name='任务ID')),
                ('applicant', models.CharField(max_length=30, verbose_name='工单申请人')),
                ('executor', models.CharField(default='', max_length=30, verbose_name='工单执行人')),
                ('host', models.CharField(max_length=128, verbose_name='主机')),
                ('database', models.CharField(max_length=80, verbose_name='库名')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('sql', models.TextField(default='', verbose_name='执行的SQL')),
                ('sql_type', models.CharField(choices=[('DDL', 'DDL工单'), ('DML', 'DML工单'), ('OPS', '运维工单'), ('EXPORT', '数据导出工单')], default='DML', max_length=5, verbose_name='SQL类型')),
                ('is_ghost', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否启用ghost改表')),
                ('ghost_pid', models.IntegerField(default=0, verbose_name='ghost进程pid')),
                ('task_progress', models.CharField(choices=[('0', '未执行'), ('1', '已完成'), ('2', '处理中'), ('3', '失败'), ('4', '异常')], default='0', max_length=10, verbose_name='任务进度')),
                ('affected_row', models.IntegerField(default=0, verbose_name='影响行数')),
                ('task_execlog', models.TextField(default='', verbose_name='任务执行的日志')),
                ('rollback_sql', models.TextField(default='', verbose_name='回滚的SQL')),
                ('file_format', models.CharField(choices=[('xlsx', 'xlsx格式'), ('csv', 'csv格式')], max_length=30, verbose_name='导出的文件格式')),
                ('consume_time', models.CharField(default='0.00', max_length=1024, verbose_name='任务耗时，单位s')),
                ('execition_time', models.DateTimeField(auto_now=True, verbose_name='工单执行时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '工单执行任务',
                'verbose_name_plural': '工单执行任务',
                'db_table': 'auditsql_orders_tasks',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SqlOrderReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('reply_contents', models.TextField(default='', verbose_name='回复内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('reply', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.Orders')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工单回复',
                'verbose_name_plural': '工单回复',
                'db_table': 'auditsql_reply',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SysEnvironment',
            fields=[
                ('envi_id', models.AutoField(primary_key=True, serialize=False, verbose_name='环境ID')),
                ('envi_name', models.CharField(default='', max_length=30, verbose_name='环境名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统环境',
                'verbose_name_plural': '系统环境',
                'db_table': 'auditsql_sys_environment',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='orderstasks',
            name='envi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SysEnvironment', verbose_name='环境'),
        ),
        migrations.AddField(
            model_name='orderstasks',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders', verbose_name='工单ID'),
        ),
        migrations.AddField(
            model_name='orders',
            name='envi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SysEnvironment'),
        ),
        migrations.AlterUniqueTogether(
            name='onlineversion',
            unique_together={('version',)},
        ),
        migrations.AddField(
            model_name='mysqlschemas',
            name='envi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SysEnvironment'),
        ),
        migrations.AddField(
            model_name='mysqlconfig',
            name='envi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SysEnvironment', verbose_name='环境'),
        ),
        migrations.AlterUniqueTogether(
            name='mysqlschemas',
            unique_together={('cid', 'schema')},
        ),
        migrations.AlterUniqueTogether(
            name='mysqlconfig',
            unique_together={('host', 'port')},
        ),
    ]
