# Generated by Django 2.1.7 on 2019-04-09 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreply',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='onlineversion',
            unique_together={('version',)},
        ),
        migrations.AddField(
            model_name='mysqlschemas',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MysqlConfig', verbose_name='主机'),
        ),
        migrations.AddField(
            model_name='mysqlschemas',
            name='envi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SysEnvironment'),
        ),
        migrations.AddField(
            model_name='mysqlconfig',
            name='envi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SysEnvironment', verbose_name='环境'),
        ),
        migrations.AddField(
            model_name='exportfiles',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.OrdersTasks', verbose_name='关联子任务的ID'),
        ),
        migrations.AlterUniqueTogether(
            name='mysqlschemas',
            unique_together={('cid', 'schema')},
        ),
        migrations.AlterUniqueTogether(
            name='mysqlconfig',
            unique_together={('host', 'port')},
        ),
    ]
