# Generated by Django 2.1.7 on 2019-03-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysqlconfig',
            old_name='rsd_type',
            new_name='rds_type',
        ),
    ]
