# Generated by Django 2.1.7 on 2019-03-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190318_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='progress',
            field=models.CharField(choices=[('0', '待批准'), ('1', '未批准'), ('2', '已批准'), ('3', '处理中'), ('4', '已完成'), ('5', '已关闭'), ('6', '已复核'), ('7', '已勾住')], default='0', max_length=30, verbose_name='任务进度'),
        ),
    ]
