# Generated by Django 2.1.7 on 2019-03-21 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20190319_1046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SqlOrderReply',
            new_name='OrderReply',
        ),
    ]
