# Generated by Django 2.1.7 on 2019-03-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190321_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(default='', max_length=256, verbose_name='名称')),
                ('key', models.CharField(default='', max_length=256, verbose_name='key')),
                ('value', models.TextField(blank=True, max_length=256, null=True, verbose_name='值')),
                ('is_enabled', models.CharField(choices=[('0', '启用'), ('1', '禁用')], default='1', max_length=2, verbose_name='是否启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'auditsql_sys_config',
                'default_permissions': (),
            },
        ),
    ]
