# Generated by Django 2.1.7 on 2019-03-26 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_sysconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='version',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.OnlineVersion'),
        ),
    ]
