# Generated by Django 2.1.7 on 2019-03-26 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190326_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.OnlineVersion'),
        ),
    ]
