# Generated by Django 2.1.7 on 2019-03-26 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190326_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('file_name', models.CharField(default='', max_length=256, verbose_name='文件名')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小，单位B')),
                ('files', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('encryption_key', models.CharField(default='', max_length=128, verbose_name='加密密钥')),
                ('content_type', models.CharField(default='', max_length=100, verbose_name='文件的类型')),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.OrdersTasks', verbose_name='关联子任务的ID')),
            ],
            options={
                'verbose_name': 'sql导出excel表',
                'verbose_name_plural': 'sql导出excel表',
                'db_table': 'auditsql_export_files',
                'default_permissions': (),
            },
        ),
    ]
