# Generated by Django 2.1.7 on 2019-03-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_exportfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstasks',
            name='sql_type',
            field=models.CharField(choices=[('DDL', 'DDL工单'), ('DML', 'DML工单'), ('OPS', '运维工单'), ('EXPORT', '数据导出工单')], default='DML', max_length=10, verbose_name='SQL类型'),
        ),
    ]
