# Generated by Django 2.1.7 on 2019-03-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_onlineversion_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
