# Generated by Django 2.2.16 on 2020-09-22 06:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('fd849fcb-cdbb-475a-800e-8c9c5c058d4a'), verbose_name='用户JWT秘钥'),
        ),
    ]
