# Generated by Django 2.2.16 on 2020-09-28 08:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200922_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='department',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('db67e529-9c1a-4455-b15b-f9ca0b30b49f'), verbose_name='用户JWT秘钥'),
        ),
    ]
