# Generated by Django 2.1.2 on 2018-12-13 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sqlorders', '0002_auto_20181213_1407'),
        ('sqlquery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlrulesgroup',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mysqlruleschain',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqlorders.MysqlConfig', verbose_name='主机'),
        ),
    ]
