# Generated by Django 2.1.2 on 2018-12-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0004_auto_20181213_1650'),
        ('sqlquery', '0002_auto_20181213_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysqlruleschain',
            name='column',
        ),
        migrations.AlterUniqueTogether(
            name='mysqlruleschain',
            unique_together={('cid', 'schema', 'table')},
        ),
    ]
