# Generated by Django 2.1.2 on 2018-12-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlquery', '0003_auto_20181213_1650'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mysqlruleschain',
            unique_together={('schema', 'table')},
        ),
    ]
