# Generated by Django 2.1.2 on 2018-12-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlquery', '0004_auto_20181213_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlruleschain',
            name='action',
            field=models.CharField(choices=[('allow', '允许')], max_length=32, verbose_name='允许规则'),
        ),
        migrations.AlterField(
            model_name='mysqlruleschain',
            name='comment',
            field=models.CharField(default='', max_length=255, verbose_name='规则'),
        ),
    ]
