# Generated by Django 2.1.1 on 2018-09-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshell', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webshellinfo',
            options={'default_permissions': (), 'verbose_name': 'webssh', 'verbose_name_plural': 'webssh'},
        ),
    ]
