# Generated by Django 2.1.1 on 2018-09-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webshellinfo',
            name='envi_id',
            field=models.IntegerField(verbose_name='环境'),
        ),
    ]
