# Generated by Django 2.1.1 on 2018-09-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshell', '0002_auto_20180915_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webshellinfo',
            name='envi',
        ),
    ]
