# Generated by Django 2.0.2 on 2018-08-15 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlockCommand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('command', models.CharField(default='', max_length=1024, verbose_name='pt-deadlock-logger命令')),
                ('schema_id', models.CharField(default='', max_length=128, verbose_name='关联MysqlSchemaInfo的id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '死锁命令表',
                'verbose_name_plural': '死锁命令表',
                'db_table': 'auditsql_deadlock_command',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DeadlockRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('server', models.CharField(max_length=20)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('thread', models.IntegerField()),
                ('txn_id', models.CharField(max_length=1024)),
                ('txn_time', models.PositiveSmallIntegerField()),
                ('user', models.CharField(max_length=16)),
                ('hostname', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=15)),
                ('db', models.CharField(max_length=64)),
                ('tbl', models.CharField(max_length=64)),
                ('idx', models.CharField(max_length=64)),
                ('lock_type', models.CharField(max_length=16)),
                ('lock_mode', models.CharField(max_length=1)),
                ('wait_hold', models.CharField(max_length=1)),
                ('victim', models.SmallIntegerField()),
                ('query', models.TextField()),
                ('is_pull', models.SmallIntegerField(default=0, verbose_name='是否已推送，0：未推送，1：已推送')),
            ],
            options={
                'verbose_name': '死锁采集记录表,pt-deadlock-logger工具采集',
                'verbose_name_plural': '死锁采集记录表,pt-deadlock-logger工具采集',
                'db_table': 'dbaudit_deadlocks_records',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MySQLQueryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('user', models.CharField(max_length=30, verbose_name='用户名')),
                ('host', models.CharField(max_length=32, verbose_name='目标数据库地址')),
                ('database', models.CharField(max_length=32, verbose_name='目标数据库')),
                ('envi', models.SmallIntegerField(default=1, verbose_name='0：线上环境， 1：线下环境')),
                ('query_sql', models.TextField(default='', verbose_name='查询SQL')),
                ('query_time', models.CharField(default='', max_length=128, verbose_name='查询时间，单位s')),
                ('query_status', models.CharField(default='', max_length=2048, verbose_name='查询状态，成功或失败的原因')),
                ('affect_rows', models.IntegerField(default=0, verbose_name='影响行数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
            ],
            options={
                'verbose_name': 'mysql查询记录日志',
                'verbose_name_plural': 'mysql查询记录日志',
                'db_table': 'auditsql_mysql_query_log',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MysqlSchemaGrant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '生产环境数据库授权',
                'verbose_name_plural': '生产环境数据库授权',
                'db_table': 'auditsql_mysql_schema_grant',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MysqlSchemaInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('user', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('host', models.CharField(max_length=32, verbose_name='地址')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('schema', models.CharField(default='', max_length=30, verbose_name='schema信息')),
                ('envi', models.SmallIntegerField(default=1, verbose_name='0: 线下其他环境，1：M1环境，2：Staging环境 3：生产环境')),
                ('is_master', models.SmallIntegerField(default=1, verbose_name='0：从库（用于查询）， 1：主库（用于审核）')),
                ('schema_join', models.CharField(default='', max_length=128, unique=True, verbose_name='host、port、schema的组合, 关联MysqlSchemaGrant的schema')),
                ('comment', models.CharField(max_length=128, null=True, verbose_name='主机描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '所有MySQL集群节点的schema汇总',
                'verbose_name_plural': '所有MySQL集群节点的schema汇总',
                'db_table': 'auditsql_mysql_schema',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MysqlSlowLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('hostname', models.CharField(default='', max_length=128, verbose_name='慢查询主机')),
                ('version', models.CharField(default='', max_length=128, verbose_name='数据库版本')),
                ('qps', models.CharField(default='0.00', max_length=128, verbose_name='区间内每秒平均查询数')),
                ('cnt', models.IntegerField(default=0, verbose_name='区间内执行总数')),
                ('avg', models.CharField(default='', max_length=128, verbose_name='区间内查询的平均响应时间')),
                ('fingerprint', models.TextField(verbose_name='SQL指纹')),
                ('md5sum', models.CharField(default='', max_length=32, verbose_name='MD5值')),
                ('is_pull', models.SmallIntegerField(default=0, verbose_name='是否钉钉推送：0：推送，1：不推送')),
                ('timerange', models.CharField(default='', max_length=128, verbose_name='时间范围')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'mysql慢查询统计表',
                'verbose_name_plural': 'mysql慢查询统计表',
                'db_table': 'auditsql_mysql_slow_log',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WebShellGrant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'web shell授权表',
                'verbose_name_plural': 'web shell授权表',
                'db_table': 'auditsql_web_shell_grant',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WebShellInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('command', models.CharField(default='', max_length=1024, verbose_name='用户命令')),
                ('envi', models.SmallIntegerField(default=1, verbose_name='0: 线下环境，1: 生产环境')),
                ('comment', models.CharField(max_length=128, null=True, verbose_name='命令描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'mongodb和redis',
                'verbose_name_plural': 'mongodb和redis',
                'db_table': 'auditsql_web_shell',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WebShellOpLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('user', models.CharField(default='', max_length=128, verbose_name='操作用户')),
                ('session_id', models.CharField(default='', max_length=128, verbose_name='会话id')),
                ('op_cmd', models.CharField(default='', max_length=4096, null=True, verbose_name='操作的命令')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'web shell操作记录表',
                'verbose_name_plural': 'web shell操作记录表',
                'db_table': 'auditsql_web_shell_oplog',
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='webshellinfo',
            unique_together={('comment',)},
        ),
        migrations.AddField(
            model_name='webshellgrant',
            name='shell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstats.WebShellInfo'),
        ),
    ]
