# Generated by Django 2.0.2 on 2018-05-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySQLQueryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('user', models.CharField(max_length=30, verbose_name='用户名')),
                ('host', models.CharField(max_length=32, verbose_name='目标数据库地址')),
                ('database', models.CharField(max_length=32, verbose_name='目标数据库')),
                ('query_sql', models.TextField(default='', verbose_name='查询SQL')),
                ('query_status', models.CharField(default='', max_length=2048, verbose_name='查询状态，成功或失败的原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
            ],
            options={
                'verbose_name': 'mysql查询记录日志',
                'verbose_name_plural': 'mysql查询记录日志',
                'db_table': 'auditsql_mysql_query_log',
                'default_permissions': (),
            },
        ),
    ]
