# Generated by Django 2.0.2 on 2018-08-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstats', '0003_auto_20180815_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlconfigsource',
            name='envi',
            field=models.SmallIntegerField(default=1, verbose_name='1：test环境，2：Staging环境 3：生产环境'),
        ),
        migrations.AlterField(
            model_name='mysqlschemainfo',
            name='schema',
            field=models.CharField(default='', max_length=64, verbose_name='schema信息'),
        ),
    ]
