# Generated by Django 2.2.16 on 2021-01-21 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedisEnv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'redis环境',
                'verbose_name_plural': 'redis环境',
                'db_table': 'yasql_redis_env',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RedisLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('host_dsn', models.CharField(max_length=255, verbose_name='redis地址')),
                ('exec_cmd', models.TextField(blank=True, verbose_name='执行命令')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': 'redis执行日志',
                'verbose_name_plural': 'redis执行日志',
                'db_table': 'yasql_redis_log',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RedisGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(max_length=32, verbose_name='redis组名')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rg_env', to='redisms.RedisEnv', verbose_name='环境')),
            ],
            options={
                'verbose_name': 'redis组',
                'verbose_name_plural': 'redis组',
                'db_table': 'yasql_redis_group',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RedisConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('host', models.CharField(max_length=128, verbose_name='地址')),
                ('port', models.IntegerField(default=6379, verbose_name='端口')),
                ('password', models.CharField(blank=True, max_length=256, null=True, verbose_name='密码')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rg', to='redisms.RedisGroup', verbose_name='redis组')),
            ],
            options={
                'verbose_name': 'redis配置',
                'verbose_name_plural': 'redis配置',
                'db_table': 'yasql_redis_config',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RedisGrant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('permission_code', models.CharField(choices=[('read_only', 'read_only'), ('read_write', 'read_write')], max_length=32, verbose_name='读写权限')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rg_group', to='redisms.RedisGroup', verbose_name='redis组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rg_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'redis授权',
                'verbose_name_plural': 'redis授权',
                'db_table': 'yasql_redis_grant',
                'default_permissions': (),
                'unique_together': {('user', 'group', 'permission_code')},
            },
        ),
    ]
