# Generated by Django 2.1.7 on 2019-03-16 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccounts',
            table='auditsql_useraccounts',
        ),
    ]
