# Generated by Django 2.1.1 on 2018-09-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='用户手机号'),
        ),
    ]
