# Generated by Django 2.1.1 on 2018-09-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180914_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='displayname',
            field=models.CharField(default='', max_length=128, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='激活'),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
