# Generated by Django 2.1.7 on 2019-03-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190316_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='displayname',
            field=models.CharField(default='', max_length=128, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
    ]
