# Generated by Django 2.1.1 on 2018-09-15 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180915_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'default_permissions': (), 'verbose_name': '权限', 'verbose_name_plural': '权限'},
        ),
        migrations.AlterModelOptions(
            name='useraccounts',
            options={'default_permissions': (), 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='userroles',
            options={'default_permissions': (), 'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
    ]
