# Generated by Django 2.1.1 on 2018-09-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('host', models.CharField(max_length=128, verbose_name='地址')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('user', models.CharField(default='', max_length=32, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=64, verbose_name='密码')),
                ('envi_id', models.IntegerField(choices=[(0, '1'), (1, '1')], verbose_name='环境')),
                ('is_master', models.SmallIntegerField(choices=[(0, '数据查询'), (1, 'SQL审核')], verbose_name='用途')),
                ('comment', models.CharField(max_length=128, null=True, verbose_name='主机描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据库主机配置',
                'verbose_name_plural': '数据库主机配置',
                'db_table': 'sqlaudit_mysql_config',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MysqlSchemas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('user', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('host', models.CharField(max_length=128, verbose_name='地址')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('schema', models.CharField(default='', max_length=64, verbose_name='schema信息')),
                ('envi_id', models.IntegerField(verbose_name='环境')),
                ('is_master', models.SmallIntegerField(verbose_name='用途, 主库：1， 从库：0')),
                ('schema_join', models.CharField(max_length=128, verbose_name='host、port、schema的组合')),
                ('comment', models.CharField(max_length=128, null=True, verbose_name='主机描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'MySQL集群汇总库',
                'verbose_name_plural': 'MySQL集群汇总库',
                'db_table': 'sqlaudit_mysql_schemas',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SqlOrdersContents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.CharField(default='', max_length=2048, verbose_name='需求url或者描述性文字')),
                ('sql_type', models.CharField(choices=[('DDL', 'DDL'), ('DML', 'DML')], default='DML', max_length=5, verbose_name='SQL类型: DDL or DML')),
                ('envi_id', models.IntegerField(choices=[(0, '1'), (1, '1')], verbose_name='环境')),
                ('proposer', models.CharField(default='', max_length=30, verbose_name='申请人， 一般为开发或者产品，存储username')),
                ('auditor', models.CharField(default='', max_length=30, verbose_name='审核人')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('email_cc', models.CharField(default='', max_length=4096, verbose_name='抄送联系人')),
                ('host', models.CharField(default='', max_length=128, verbose_name='mysql主机')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('database', models.CharField(default='', max_length=80, verbose_name='库名')),
                ('progress', models.CharField(choices=[('0', '待批准'), ('1', '未批准'), ('2', '已批准'), ('3', '处理中'), ('4', '已完成'), ('5', '已关闭'), ('6', '已勾住')], default='0', max_length=10, verbose_name='任务进度')),
                ('remark', models.CharField(default='', max_length=32, verbose_name='工单备注')),
                ('task_version', models.CharField(default='', max_length=256, verbose_name='上线任务版本')),
                ('close_user', models.CharField(default='', max_length=30, verbose_name='关闭记录的用户')),
                ('close_reason', models.CharField(default='', max_length=1024, verbose_name='关闭原因')),
                ('close_time', models.DateTimeField(auto_now_add=True, verbose_name='关闭时间')),
                ('contents', models.TextField(default='', verbose_name='提交的内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工单记录',
                'verbose_name_plural': '工单记录',
                'db_table': 'sqlaudit_sql_orders_contents',
            },
        ),
        migrations.CreateModel(
            name='SqlOrdersEnvironment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('envi_id', models.IntegerField(default=1, verbose_name='ID，起始值：1')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父ID，起始值：0')),
                ('envi_name', models.CharField(default='', max_length=30, verbose_name='环境')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '环境配置',
                'verbose_name_plural': '环境配置',
                'db_table': 'sqlaudit_sql_order_environment',
            },
        ),
        migrations.CreateModel(
            name='SqlOrdersExecTasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('uid', models.IntegerField(default=0, verbose_name='操作用户uid')),
                ('user', models.CharField(max_length=30, verbose_name='操作用户')),
                ('taskid', models.CharField(max_length=128, verbose_name='任务号')),
                ('related_id', models.IntegerField(default=0, verbose_name='关联SqlOrdersContents的主键id')),
                ('envi_id', models.IntegerField(choices=[(0, '1'), (1, '1')], verbose_name='环境')),
                ('host', models.CharField(max_length=30, verbose_name='操作目标数据库主机')),
                ('database', models.CharField(max_length=80, verbose_name='操作目标数据库')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('sql', models.TextField(default='', verbose_name='执行的SQL')),
                ('sql_type', models.CharField(choices=[('DDL', 'DDL'), ('DML', 'DML')], default='DML', max_length=5, verbose_name='SQL类型')),
                ('sqlsha1', models.CharField(default='', max_length=120, verbose_name='sqlsha1')),
                ('rollback_sqlsha1', models.CharField(default='', max_length=120, verbose_name='rollback sqlsha1')),
                ('celery_task_id', models.CharField(default='', max_length=256, verbose_name='celery执行任务ID')),
                ('exec_status', models.CharField(choices=[('0', '未执行'), ('1', '已完成'), ('2', '处理中'), ('3', '回滚中'), ('4', '已回滚'), ('5', '失败'), ('6', '异常')], default='0', max_length=10, verbose_name='执行进度')),
                ('sequence', models.CharField(default='', max_length=1024, verbose_name='备份记录id，inception生成的sequence')),
                ('affected_row', models.IntegerField(default=0, verbose_name='预计影响行数')),
                ('backup_dbname', models.CharField(default='', max_length=1024, verbose_name='inception生成的备份的库名')),
                ('exec_log', models.TextField(default='', verbose_name='执行的记录')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '工单执行任务',
                'verbose_name_plural': '工单执行任务',
                'db_table': 'sqlaudit_sql_orders_execute_tasks',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SqlOrdersTasksVersions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('username', models.CharField(default='', max_length=128, verbose_name='创建用户')),
                ('tasks_version', models.CharField(default='', max_length=128, verbose_name='任务版本')),
                ('expire_time', models.DateTimeField(default='2000-11-01 01:01:01', verbose_name='任务截止上线日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'SQL工单上线任务版本',
                'verbose_name_plural': 'SQL工单上线任务版本',
                'db_table': 'sqlaudit_sql_orders_tasks_versions',
            },
        ),
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(default='', max_length=256, verbose_name='名称')),
                ('key', models.CharField(default='', max_length=256, verbose_name='key')),
                ('value', models.CharField(blank=True, max_length=256, null=True, verbose_name='值')),
                ('is_enabled', models.CharField(choices=[('0', '启用'), ('1', '禁用')], default='1', max_length=2, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'sqlaudit_sys_config',
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='sqlorderstasksversions',
            unique_together={('tasks_version',)},
        ),
        migrations.AlterUniqueTogether(
            name='sqlordersenvironment',
            unique_together={('envi_id',), ('parent_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='mysqlschemas',
            unique_together={('schema_join',), ('host', 'port', 'schema')},
        ),
        migrations.AlterUniqueTogether(
            name='mysqlconfig',
            unique_together={('host', 'port')},
        ),
    ]
