# Generated by Django 2.1.2 on 2018-12-13 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sqlorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlorderreply',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sqlexportfiles',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sqlorders.SqlOrdersExecTasks', verbose_name='关联执行任务的主键id'),
        ),
        migrations.AddField(
            model_name='mysqlschemas',
            name='cid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sqlorders.MysqlConfig', verbose_name='主机'),
        ),
        migrations.AddField(
            model_name='mysqlschemas',
            name='envi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sqlorders.SqlOrdersEnvironment'),
        ),
        migrations.AddField(
            model_name='mysqlconfig',
            name='envi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sqlorders.SqlOrdersEnvironment'),
        ),
        migrations.AlterUniqueTogether(
            name='mysqlschemas',
            unique_together={('host', 'port', 'schema')},
        ),
        migrations.AlterUniqueTogether(
            name='mysqlconfig',
            unique_together={('host', 'port')},
        ),
    ]
