# Generated by Django 2.1.1 on 2018-09-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0002_auto_20180914_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqlordersenvironment',
            options={'verbose_name': '环境配置', 'verbose_name_plural': '环境配置'},
        ),
        migrations.AlterField(
            model_name='mysqlconfig',
            name='envi_id',
            field=models.IntegerField(choices=[(1, '生产环境'), (2, '预发布环境'), (3, '测试环境')], verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='sqlorderscontents',
            name='envi_id',
            field=models.IntegerField(choices=[(1, '生产环境'), (2, '预发布环境'), (3, '测试环境')], verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='sqlordersenvironment',
            name='envi_id',
            field=models.IntegerField(default=1, verbose_name='当前环境id，起始值：1'),
        ),
        migrations.AlterField(
            model_name='sqlordersenvironment',
            name='envi_name',
            field=models.CharField(default='', max_length=30, verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='sqlordersenvironment',
            name='parent_id',
            field=models.IntegerField(default=0, verbose_name='上一级环境id，起始值：0'),
        ),
        migrations.AlterField(
            model_name='sqlordersexectasks',
            name='envi_id',
            field=models.IntegerField(choices=[(1, '生产环境'), (2, '预发布环境'), (3, '测试环境')], verbose_name='环境'),
        ),
    ]
