# Generated by Django 2.1.2 on 2018-12-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0002_auto_20181213_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlordersenvironment',
            name='envi_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='环境ID'),
        ),
    ]
