# Generated by Django 2.1.1 on 2018-09-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0003_auto_20180917_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlconfig',
            name='envi_id',
            field=models.IntegerField(choices=[(1, '生产环境'), (2, '预发布环境'), (3, '测试环境')], verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='sqlorderscontents',
            name='envi_id',
            field=models.IntegerField(choices=[(1, '生产环境'), (2, '预发布环境'), (3, '测试环境')], verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='sqlordersexectasks',
            name='envi_id',
            field=models.IntegerField(choices=[(1, '生产环境'), (2, '预发布环境'), (3, '测试环境')], verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='sqlordersexectasks',
            name='host',
            field=models.CharField(max_length=128, verbose_name='操作目标数据库主机'),
        ),
    ]
