# Generated by Django 2.1.1 on 2018-09-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0004_auto_20180918_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysconfig',
            name='value',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='值'),
        ),
    ]
