# Generated by Django 2.1.2 on 2018-12-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0004_auto_20181213_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlconfig',
            name='character',
            field=models.CharField(choices=[('utf8', 'utf8'), ('utf8mb4', 'utf8mb4'), ('latin1', 'latin1')], default='utf8', max_length=32, verbose_name='库表字符集'),
        ),
        migrations.AddField(
            model_name='mysqlschemas',
            name='character',
            field=models.CharField(default='utf8', max_length=32, verbose_name='库表字符集'),
        ),
    ]
