# Generated by Django 2.1.5 on 2019-01-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0005_auto_20181214_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlconfig',
            name='database_type',
            field=models.SmallIntegerField(choices=[(0, '非阿里云RDS'), (1, '阿里云RDS')], default=0, verbose_name='数据库的类型'),
        ),
        migrations.AlterField(
            model_name='mysqlconfig',
            name='character',
            field=models.CharField(choices=[('utf8', 'utf8'), ('utf8mb4', 'utf8mb4')], default='utf8', max_length=32, verbose_name='库表字符集'),
        ),
    ]
