# Generated by Django 2.1.1 on 2018-09-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0006_sqlordersexectasks_is_ghost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlordersexectasks',
            name='ghost_pid',
            field=models.IntegerField(default=0, verbose_name='ghost进程pid'),
        ),
    ]
