# Generated by Django 2.1.2 on 2018-10-10 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sqlorders', '0007_sqlordersexectasks_ghost_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlOrderReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('reply_contents', models.TextField(default='', verbose_name='回复内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('reply', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sqlorders.SqlOrdersContents')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工单回复',
                'verbose_name_plural': '工单回复',
                'db_table': 'sqlaudit_sql_order_reply',
                'default_permissions': (),
            },
        ),
    ]
