# Generated by Django 2.1.2 on 2018-10-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0008_sqlorderreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlordersexectasks',
            name='execition_time',
            field=models.DateTimeField(auto_now=True, verbose_name='工单执行时间'),
        ),
        migrations.AddField(
            model_name='sqlordersexectasks',
            name='executor',
            field=models.CharField(default='', max_length=30, verbose_name='工单执行人'),
        ),
        migrations.AddField(
            model_name='sqlordersexectasks',
            name='runtime',
            field=models.CharField(default='0.00', max_length=1024, verbose_name='任务运行时间，单位s'),
        ),
        migrations.AlterField(
            model_name='sqlordersexectasks',
            name='uid',
            field=models.IntegerField(default=0, verbose_name='申请用户uid'),
        ),
        migrations.AlterField(
            model_name='sqlordersexectasks',
            name='user',
            field=models.CharField(max_length=30, verbose_name='申请用户'),
        ),
    ]
