# Generated by Django 2.1.2 on 2018-10-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0010_auto_20181025_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlordersexectasks',
            name='celery_task_id',
        ),
        migrations.AlterField(
            model_name='sqlordersexectasks',
            name='exec_status',
            field=models.CharField(choices=[('0', '未执行'), ('1', '已完成'), ('2', '处理中'), ('5', '失败')], default='0', max_length=10, verbose_name='执行进度'),
        ),
    ]
