# Generated by Django 2.1.2 on 2018-11-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0011_auto_20181025_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlorderscontents',
            name='description',
            field=models.CharField(default='', max_length=2048, verbose_name='需求'),
        ),
        migrations.AlterField(
            model_name='sqlorderscontents',
            name='email_cc',
            field=models.CharField(default='', max_length=4096, verbose_name='抄送人'),
        ),
        migrations.AlterField(
            model_name='sqlorderscontents',
            name='host',
            field=models.CharField(default='', max_length=128, verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='sqlorderscontents',
            name='proposer',
            field=models.CharField(default='', max_length=30, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='sqlorderscontents',
            name='remark',
            field=models.CharField(default='', max_length=32, verbose_name='备注'),
        ),
    ]
