# Generated by Django 2.1.2 on 2018-11-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0012_auto_20181102_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlconfig',
            name='is_master',
            field=models.SmallIntegerField(choices=[(0, '查询_只读'), (1, 'SQL审核'), (2, '查询_读写')], default=0, verbose_name='用途'),
        ),
        migrations.AlterField(
            model_name='sqlorderscontents',
            name='sql_type',
            field=models.CharField(choices=[('DDL', 'DDL'), ('DML', 'DML'), ('OPS', 'OPS')], default='DML', max_length=5, verbose_name='类型: DDL 、DML or OPS'),
        ),
        migrations.AlterField(
            model_name='sqlordersexectasks',
            name='sql_type',
            field=models.CharField(choices=[('DDL', 'DDL'), ('DML', 'DML'), ('OPS', 'OPS')], default='DML', max_length=5, verbose_name='SQL类型'),
        ),
    ]
