# Generated by Django 2.1.2 on 2018-11-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0013_auto_20181107_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlordersenvironment',
            name='parent_id',
        ),
        migrations.AlterUniqueTogether(
            name='sqlordersenvironment',
            unique_together={('envi_id',)},
        ),
    ]
