# Generated by Django 2.1.2 on 2018-11-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0014_auto_20181107_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysqlconfig',
            old_name='is_master',
            new_name='is_type',
        ),
    ]
