# Generated by Django 2.1.2 on 2018-11-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0016_auto_20181107_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlExportFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('file_name', models.CharField(default='', max_length=256, verbose_name='文件名')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小，单位B')),
                ('files', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('content_type', models.CharField(default='', max_length=100, verbose_name='文件的类型')),
                ('task', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sqlorders.SqlOrdersExecTasks', verbose_name='关联执行任务的主键id')),
            ],
            options={
                'verbose_name': 'sql导出excel表',
                'verbose_name_plural': 'sql导出excel表',
                'db_table': 'sqlaudit_sql_export_excel',
                'default_permissions': (),
            },
        ),
    ]
