# Generated by Django 2.0.2 on 2018-08-15 08:22

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='用户uid')),
                ('avatar_file', models.ImageField(default='img/avatar1.png', upload_to='img/%Y/%m/%d/', verbose_name='用户头像')),
                ('displayname', models.CharField(default='', max_length=128, verbose_name='用户显示名')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('mobile', models.CharField(default='', max_length=11, verbose_name='用户手机号')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
                'db_table': 'auditsql_useraccount',
                'default_permissions': (),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PermissionDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '权限详情表',
                'verbose_name_plural': '权限详情表',
                'db_table': 'auditsql_permission_detail',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('permission_name', models.CharField(max_length=30, verbose_name='权限名')),
                ('permission_desc', models.CharField(default='', max_length=30, verbose_name='权限描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '内置权限',
                'verbose_name_plural': '内置权限',
                'db_table': 'auditsql_permission',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('role_name', models.CharField(max_length=30, verbose_name='角色名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'auditsql_roles',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RolesDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.Roles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户角色分组详情表',
                'verbose_name_plural': '用户角色分组详情表',
                'db_table': 'auditsql_roles_detail',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SystemMsg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('title', models.CharField(default='', max_length=64, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统消息推送表',
                'verbose_name_plural': '系统消息推送表',
                'db_table': 'auditsql_system_msg',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SystemMsgDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.SystemMsg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '系统消息推送详情表',
                'verbose_name_plural': '系统消息推送详情表',
                'db_table': 'auditsql_system_msg_details',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='permissiondetail',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.RolePermission'),
        ),
        migrations.AddField(
            model_name='permissiondetail',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.Roles'),
        ),
        migrations.AlterUniqueTogether(
            name='rolesdetail',
            unique_together={('user',)},
        ),
    ]
