# Generated by Django 2.0.2 on 2018-06-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'default_permissions': (), 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'default_permissions': (), 'verbose_name': '内置权限', 'verbose_name_plural': '内置权限'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'default_permissions': (), 'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'default_permissions': (), 'verbose_name': '账户', 'verbose_name_plural': '账户'},
        ),
    ]
