# Generated by Django 2.0.2 on 2018-02-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'default_permissions': (), 'verbose_name': '项目组表', 'verbose_name_plural': '项目组表'},
        ),
        migrations.AlterModelOptions(
            name='groupsdetail',
            options={'default_permissions': (), 'verbose_name': '项目组详情表', 'verbose_name_plural': '项目组详情表'},
        ),
    ]
