# Generated by Django 2.0.2 on 2018-04-17 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('permission_name', models.CharField(max_length=30, verbose_name='权限名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色权限',
                'verbose_name_plural': '角色权限',
                'db_table': 'auditsql_permission',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PermissionDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Roles')),
            ],
            options={
                'verbose_name': '权限详情表',
                'verbose_name_plural': '权限详情表',
                'db_table': 'auditsql_permission_detail',
                'default_permissions': (),
            },
        ),
    ]
