# Generated by Django 2.0.2 on 2018-04-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_permission_permissiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='permission_desc',
            field=models.CharField(default='', max_length=30, verbose_name='权限描述'),
        ),
    ]
