# Generated by Django 2.0.2 on 2018-02-06 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_auto_20180206_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Contacts')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Groups')),
            ],
            options={
                'verbose_name': '联系人详情表',
                'verbose_name_plural': '联系人详情表',
                'db_table': 'auditsql_contacts_detail',
                'default_permissions': (),
            },
        ),
    ]
