# Generated by Django 2.0.2 on 2018-02-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0003_auto_20180202_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar_file',
            field=models.ImageField(default='img/avatar1.png', upload_to='img/%Y/%m/%d/', verbose_name='用户头像'),
        ),
    ]
