# Generated by Django 2.0.2 on 2018-02-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0004_auto_20180206_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsdetail',
            name='bcc',
            field=models.IntegerField(default=0, verbose_name='0:不密送，1:密送'),
        ),
    ]
