# Generated by Django 2.0.2 on 2018-03-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0011_auto_20180224_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('ldap_url', models.CharField(default='', max_length=512, verbose_name='ldap服务器地址')),
                ('bind_dn', models.CharField(default='', max_length=128, verbose_name='ldap认证用户')),
                ('bind_password', models.CharField(default='', max_length=128, verbose_name='ldap认证用户密码')),
                ('ldap_search', models.CharField(default='', max_length=1024, verbose_name='ldap用户搜索范围')),
                ('map_username', models.CharField(default='', max_length=128, verbose_name='映射的用户名(一般为字符)')),
                ('map_email', models.CharField(default='', max_length=128, verbose_name='映射的邮箱')),
                ('map_displayname', models.CharField(default='', max_length=128, verbose_name='映射的用户别名(一般为中文)')),
                ('is_enable_tls', models.CharField(choices=[('1', '启用'), ('0', '禁用')], default='0', max_length=1, verbose_name='是否启用tls加密支持')),
            ],
            options={
                'verbose_name': 'ldap配置',
                'verbose_name_plural': 'ldap配置',
                'db_table': 'auditsql_ldap_config',
                'default_permissions': (),
            },
        ),
    ]
