# Generated by Django 2.0.2 on 2018-03-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0012_ldapuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LdapUser',
        ),
    ]
