# Generated by Django 2.1.7 on 2019-03-29 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mysqlquerylog',
            options={'default_permissions': (), 'verbose_name': '查询日志', 'verbose_name_plural': '查询日志'},
        ),
    ]
