# Generated by Django 2.1.7 on 2019-04-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20190402_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mysqlprivblacklist',
            options={'default_permissions': (), 'verbose_name': '权限黑名单', 'verbose_name_plural': '权限黑名单'},
        ),
        migrations.AlterUniqueTogether(
            name='mysqlprivblacklist',
            unique_together={('schema', 'table')},
        ),
        migrations.AlterModelTable(
            name='mysqlprivblacklist',
            table='auditsql_mysql_priv_blacklist',
        ),
    ]
