# Generated by Django 2.1.7 on 2019-04-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20190402_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mysqlusergroupmap',
            options={'default_permissions': (), 'verbose_name': '权限用户映射', 'verbose_name_plural': '权限用户映射'},
        ),
        migrations.AlterModelTable(
            name='mysqlusergroupmap',
            table='auditsql_mysql_usergroup_map',
        ),
    ]
