# Generated by Django 2.1.7 on 2019-04-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_auto_20190402_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlusergroupmap',
            name='comment',
            field=models.CharField(default='', max_length=255, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='mysqlusergroupmap',
            name='group',
            field=models.CharField(default='', max_length=128, verbose_name='MySQL用户权限组'),
        ),
    ]
