# Generated by Django 2.1.7 on 2019-04-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_auto_20190402_1555'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mysqlusergroupmap',
            unique_together={('comment', 'group')},
        ),
    ]
