# Generated by Django 2.1.7 on 2019-04-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0008_auto_20190402_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlusergroupmap',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MysqlConfig', verbose_name='备注'),
        ),
    ]
