# Generated by Django 2.1.7 on 2019-04-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0009_auto_20190402_1631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mysqlruleschain',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mysqlruleschain',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='mysqlrulesgroup',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='mysqlrulesgroup',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='mysqlprivblacklist',
            options={'default_permissions': (), 'verbose_name': '库表黑名单', 'verbose_name_plural': '库表黑名单'},
        ),
        migrations.AlterModelOptions(
            name='mysqlusergroupmap',
            options={'default_permissions': (), 'verbose_name': '库表权限组', 'verbose_name_plural': '库表权限组'},
        ),
        migrations.DeleteModel(
            name='MysqlRulesChain',
        ),
        migrations.DeleteModel(
            name='MysqlRulesGroup',
        ),
    ]
