# Generated by Django 2.1.7 on 2019-04-03 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0010_auto_20190403_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlusergroupmap',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
