# Generated by Django 2.1.7 on 2019-04-03 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0011_auto_20190403_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlusergroupmap',
            name='schema',
            field=models.CharField(default='', max_length=128, verbose_name='库'),
        ),
        migrations.AlterField(
            model_name='mysqlusergroupmap',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MysqlConfig', verbose_name='主机描述'),
        ),
        migrations.AlterField(
            model_name='mysqlusergroupmap',
            name='group',
            field=models.CharField(default='', max_length=128, verbose_name='MySQL用户组名'),
        ),
        migrations.AlterField(
            model_name='mysqlusergroupmap',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
