# Generated by Django 2.1.7 on 2019-04-06 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0013_auto_20190328_1131'),
        ('query', '0012_auto_20190403_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryBusinessGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('group', models.CharField(default='', max_length=128, verbose_name='业务组名')),
                ('schema', models.CharField(default='', max_length=128, verbose_name='关联库')),
                ('tables', models.TextField(verbose_name='关联表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.MysqlConfig', verbose_name='关联主机')),
                ('map_mysqluser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.MysqlUserGroupMap', verbose_name='映射的mysql用户')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '库表业务组',
                'verbose_name_plural': '库表业务组',
                'db_table': 'yops_query_business_group',
                'default_permissions': (),
            },
        ),
    ]
