# Generated by Django 2.0.2 on 2018-03-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncepMakeExecTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('uid', models.IntegerField(default=0, verbose_name='操作用户uid')),
                ('user', models.CharField(max_length=30, verbose_name='操作用户')),
                ('taskid', models.CharField(max_length=128, verbose_name='任务号')),
                ('related_id', models.IntegerField(default=0, verbose_name='关联OnlineAuditContents的主键id')),
                ('category', models.CharField(choices=[('0', '线下任务'), ('1', '线上任务')], default='0', max_length=2, verbose_name='任务分类')),
                ('dst_host', models.CharField(max_length=30, verbose_name='操作目标数据库主机')),
                ('dst_database', models.CharField(max_length=80, verbose_name='操作目标数据库')),
                ('sql_content', models.TextField(default='', verbose_name='执行的SQL')),
                ('type', models.CharField(choices=[('DDL', '数据库定义语言'), ('DML', '数据库操纵语言')], default='', max_length=5)),
                ('sqlsha1', models.CharField(default='', max_length=120, verbose_name='sqlsha1')),
                ('rollback_sqlsha1', models.CharField(default='', max_length=120, verbose_name='sqlsha1')),
                ('exec_status', models.CharField(choices=[('0', '未执行'), ('1', '已完成'), ('2', '处理中'), ('3', '回滚中'), ('4', '已回滚')], default='0', max_length=10, verbose_name='执行进度')),
                ('sequence', models.CharField(default='', max_length=1024, verbose_name='备份记录id，inception生成的sequence')),
                ('backup_dbname', models.CharField(default='', max_length=1024, verbose_name='inception生成的备份的库名')),
                ('exec_log', models.TextField(default='', verbose_name='执行成功的记录')),
                ('make_time', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '生成Inception执行任务',
                'verbose_name_plural': '生成Inception执行任务',
                'db_table': 'sqlaudit_incep_tasks',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InceptionHostConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('user', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('host', models.CharField(max_length=32, verbose_name='ip地址')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('type', models.IntegerField(default=0, verbose_name='0:线下数据库，1:线上数据库')),
                ('is_enable', models.IntegerField(default=0, verbose_name='0:启用，1：禁用')),
                ('comment', models.CharField(max_length=128, verbose_name='主机描述')),
            ],
            options={
                'verbose_name': '数据库连接账号',
                'verbose_name_plural': '数据库连接账号',
                'db_table': 'sqlaudit_inception_hostconfig',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InceptionHostConfigDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'inception主机分组',
                'verbose_name_plural': 'inception主机分组',
                'db_table': 'auditsql_inception_hostconfig_detail',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MonitorSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_schema', models.CharField(max_length=512)),
                ('table_name', models.CharField(max_length=512)),
                ('table_stru', models.TextField(default='')),
                ('md5_sum', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '监控表结构变更表',
                'verbose_name_plural': '监控表结构变更表',
                'db_table': 'sqlaudit_monitor_schema',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OnlineAuditContents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('op_action', models.CharField(default='', max_length=100, verbose_name='审核类型，数据修改or表结构变更')),
                ('dst_host', models.CharField(default='', max_length=30, verbose_name='操作目标数据库主机')),
                ('dst_database', models.CharField(default='', max_length=80, verbose_name='操作目标数据库')),
                ('type', models.CharField(choices=[('DDL', '数据库定义语言'), ('DML', '数据库操纵语言')], default='', max_length=5)),
                ('remark', models.CharField(default='', max_length=30, verbose_name='备注')),
                ('proposer', models.CharField(default='', max_length=30, verbose_name='申请人')),
                ('verifier', models.CharField(default='', max_length=30, verbose_name='批准人')),
                ('operate_dba', models.CharField(default='', max_length=30, verbose_name='执行dba')),
                ('email_cc', models.CharField(default='', max_length=1024, verbose_name='抄送人')),
                ('progress_status', models.CharField(choices=[('0', '待批准'), ('1', '未批准'), ('2', '已批准'), ('3', '处理中'), ('4', '已完成'), ('5', '已关闭')], default='0', max_length=10, verbose_name='进度')),
                ('contents', models.TextField(default='', verbose_name='提交的内容')),
                ('fact_verifier', models.CharField(default='', max_length=30, verbose_name='实际审批人')),
                ('verifier_time', models.DateTimeField(auto_now_add=True, verbose_name='leader审批时间')),
                ('fact_operate_dba', models.CharField(default='', max_length=30, verbose_name='实际执行dba')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='DBA处理的时间')),
                ('close_user', models.CharField(default='', max_length=30, verbose_name='关闭记录的用户')),
                ('close_reason', models.CharField(default='', max_length=1024, verbose_name='关闭原因')),
                ('close_time', models.DateTimeField(auto_now_add=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '线上操作审计表',
                'verbose_name_plural': '线上操作审计表',
                'db_table': 'sqlaudit_audit_contents',
                'permissions': (('leader_verify', '批准权限'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OnlineAuditContentsReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('reply_contents', models.TextField(default='', verbose_name='回复内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('reply', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.OnlineAuditContents')),
            ],
            options={
                'verbose_name': '回复表',
                'verbose_name_plural': '回复表',
                'db_table': 'sqlaudit_audit_contents_reply',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('remark', models.CharField(default='', max_length=30, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '线上操作备注',
                'verbose_name_plural': '线上操作备注',
                'db_table': 'sqlaudit_audit_remark',
                'default_permissions': (),
            },
        ),
    ]
