# Generated by Django 2.0.2 on 2018-03-26 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineauditcontentsreply',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlineauditcontents',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Groups', verbose_name='项目组id'),
        ),
        migrations.AddField(
            model_name='inceptionhostconfigdetail',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.InceptionHostConfig'),
        ),
        migrations.AddField(
            model_name='inceptionhostconfigdetail',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Groups'),
        ),
        migrations.AlterUniqueTogether(
            name='inceptionhostconfig',
            unique_together={('host',)},
        ),
        migrations.AddField(
            model_name='incepmakeexectask',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Groups', verbose_name='项目组id'),
        ),
        migrations.AlterUniqueTogether(
            name='onlineauditcontents',
            unique_together={('title',)},
        ),
    ]
