# Generated by Django 2.0.2 on 2018-02-05 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManager', '0001_initial'),
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineauditcontents',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Groups', verbose_name='项目组id'),
        ),
        migrations.AlterUniqueTogether(
            name='onlineauditcontents',
            unique_together={('title',)},
        ),
    ]
