# Generated by Django 2.0.2 on 2018-03-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_auto_20180326_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('domain_name', models.CharField(default='', max_length=256, verbose_name='域名地址')),
            ],
            options={
                'verbose_name': '域名地址',
                'verbose_name_plural': '域名地址',
                'db_table': 'sqlaudit_domain_name',
                'default_permissions': (),
            },
        ),
    ]
