# Generated by Django 2.0.2 on 2018-03-29 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
        ('ProjectManager', '0003_domainname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('dst_host', models.CharField(default='', max_length=30, verbose_name='操作目标数据库主机')),
                ('dst_database', models.CharField(default='', max_length=80, verbose_name='操作目标数据库')),
                ('proposer', models.CharField(default='', max_length=30, verbose_name='申请人')),
                ('operate_dba', models.CharField(default='', max_length=30, verbose_name='执行dba')),
                ('email_cc', models.CharField(default='', max_length=1024, verbose_name='抄送人')),
                ('file_coding', models.CharField(default='', max_length=256, verbose_name='文件编码')),
                ('file_fomat', models.CharField(default='', max_length=256, verbose_name='文件格式')),
                ('contents', models.TextField(default='', verbose_name='提交的内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Groups', verbose_name='项目组id')),
            ],
            options={
                'verbose_name': '数据导出',
                'verbose_name_plural': '数据导出',
                'db_table': 'sqlaudit_data_export',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('file_name', models.CharField(default='', max_length=256, verbose_name='文件名')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小，单位B')),
                ('files', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('encryption_key', models.CharField(default='', max_length=128, verbose_name='加密秘钥')),
                ('content_type', models.CharField(default='', max_length=100, verbose_name='文件的类型')),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.DataExport', verbose_name='导出id')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Groups', verbose_name='项目组id')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'db_table': 'sqlaudit_files',
                'default_permissions': (),
            },
        ),
    ]
