# Generated by Django 2.0.2 on 2018-03-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_dataexport_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataexport',
            name='file_fomat',
        ),
        migrations.AddField(
            model_name='dataexport',
            name='file_format',
            field=models.CharField(default='', max_length=256, verbose_name='文件格式'),
        ),
    ]
