# Generated by Django 2.0.2 on 2018-02-06 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectManager', '0005_auto_20180206_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineAuditContentsReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('reply_contents', models.TextField(default='', verbose_name='回复内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('reply', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.OnlineAuditContents')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '回复表',
                'verbose_name_plural': '回复表',
                'db_table': 'sqlaudit_audit_contents_reply',
                'default_permissions': (),
            },
        ),
    ]
