# Generated by Django 2.0.2 on 2018-02-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_onlineauditcontentsreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionhostconfig',
            name='type',
            field=models.IntegerField(default=0, verbose_name='0:线下数据库，1:线上数据库'),
        ),
    ]
