# Generated by Django 2.0.2 on 2018-02-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0007_inceptionhostconfig_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionhostconfig',
            name='is_enable',
            field=models.IntegerField(default=0, verbose_name='0:启用，1：禁用'),
        ),
    ]
