# Generated by Django 2.0.2 on 2018-03-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0007_dataexport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='group',
        ),
    ]
