# Generated by Django 2.0.2 on 2018-04-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0008_remove_files_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='incepmakeexectask',
            name='affect_row',
            field=models.IntegerField(default=0, verbose_name='预计影响行数'),
        ),
    ]
