# Generated by Django 2.0.2 on 2018-02-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0009_auto_20180209_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineauditcontents',
            old_name='op_type',
            new_name='op_action',
        ),
    ]
