# Generated by Django 2.0.2 on 2018-04-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0009_incepmakeexectask_affect_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incepmakeexectask',
            old_name='affect_row',
            new_name='affected_row',
        ),
    ]
