# Generated by Django 2.0.2 on 2018-04-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0010_auto_20180403_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionhostconfig',
            name='protection_user',
            field=models.CharField(default='root', max_length=1024, verbose_name='被保护的数据库账号， 以逗号分隔'),
        ),
    ]
