# Generated by Django 2.0.2 on 2018-02-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0010_auto_20180209_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_schema', models.CharField(max_length=512)),
                ('table_name', models.CharField(max_length=512)),
                ('table_stru', models.TextField(default='')),
                ('md5_sum', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '监控表结构变更表',
                'verbose_name_plural': '监控表结构变更表',
                'db_table': 'dbaudit_monitor_schema',
                'permissions': (),
            },
        ),
    ]
