# Generated by Django 2.0.2 on 2018-02-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0011_monitorschema'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monitorschema',
            table='sqlaudit_monitor_schema',
        ),
    ]
