# Generated by Django 2.0.2 on 2018-04-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0011_inceptionhostconfig_protection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inceptionhostconfig',
            name='protection_user',
            field=models.TextField(default='root', verbose_name='被保护的数据库账号， 以逗号分隔'),
        ),
    ]
