# Generated by Django 2.0.2 on 2018-04-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0012_auto_20180412_1538'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dataexport',
            table='auditsql_data_export',
        ),
        migrations.AlterModelTable(
            name='domainname',
            table='auditsql_domain_name',
        ),
        migrations.AlterModelTable(
            name='files',
            table='auditsql_files',
        ),
        migrations.AlterModelTable(
            name='incepmakeexectask',
            table='auditsql_incep_tasks',
        ),
        migrations.AlterModelTable(
            name='inceptionhostconfig',
            table='auditsql_inception_hostconfig',
        ),
        migrations.AlterModelTable(
            name='monitorschema',
            table='auditsql_monitor_schema',
        ),
        migrations.AlterModelTable(
            name='onlineauditcontents',
            table='auditsql_audit_contents',
        ),
        migrations.AlterModelTable(
            name='onlineauditcontentsreply',
            table='auditsql_audit_contents_reply',
        ),
        migrations.AlterModelTable(
            name='remark',
            table='auditsql_audit_remark',
        ),
    ]
