# Generated by Django 2.0.2 on 2018-02-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0011_auto_20180224_1403'),
        ('ProjectManager', '0012_auto_20180226_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionhostconfig',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserManager.Groups', verbose_name='项目组id'),
            preserve_default=False,
        ),
    ]
