# Generated by Django 2.0.2 on 2018-02-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0011_auto_20180224_1403'),
        ('ProjectManager', '0013_inceptionhostconfig_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='InceptionHostConfigDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Groups')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.InceptionHostConfig')),
            ],
            options={
                'verbose_name': 'inception主机分组',
                'verbose_name_plural': 'inception主机分组',
                'db_table': 'auditsql_inception_hostconfig_detail',
                'default_permissions': (),
            },
        ),
    ]
