# Generated by Django 2.0.2 on 2018-02-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0014_inceptionhostconfigdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inceptionhostconfig',
            name='group',
        ),
    ]
