# Generated by Django 2.0.2 on 2018-02-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0015_remove_inceptionhostconfig_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inceptionhostconfigdetail',
            old_name='host',
            new_name='config',
        ),
    ]
