# Generated by Django 2.0.2 on 2018-02-28 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0017_auto_20180227_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remark',
            options={'default_permissions': (), 'verbose_name': '审核备注表', 'verbose_name_plural': '审核备注表'},
        ),
    ]
