# Generated by Django 2.0.2 on 2018-03-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0018_auto_20180228_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncepMakeExecTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('uid', models.IntegerField(default=0, verbose_name='操作用户uid')),
                ('user', models.CharField(max_length=30, verbose_name='操作用户')),
                ('taskid', models.CharField(max_length=128, verbose_name='任务号')),
                ('dst_host', models.CharField(max_length=30, verbose_name='操作目标数据库主机')),
                ('dst_database', models.CharField(max_length=80, verbose_name='操作目标数据库')),
                ('make_time', models.CharField(default='0.000', max_length=128, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '生成Inception执行任务',
                'verbose_name_plural': '生成Inception执行任务',
                'db_table': 'sqlaudit_incep_make_exec_task',
                'default_permissions': (),
            },
        ),
    ]
