# Generated by Django 2.0.2 on 2018-03-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0019_incepmakeexectask'),
    ]

    operations = [
        migrations.AddField(
            model_name='incepmakeexectask',
            name='sql_content',
            field=models.TextField(default='', verbose_name='执行的SQL'),
        ),
    ]
