# Generated by Django 2.0.2 on 2018-03-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0021_auto_20180306_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='incepmakeexectask',
            name='sqlsha1',
            field=models.CharField(default='', max_length=120, verbose_name='操作目标数据库'),
        ),
    ]
