# Generated by Django 2.0.2 on 2018-03-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0022_incepmakeexectask_sqlsha1'),
    ]

    operations = [
        migrations.AddField(
            model_name='incepmakeexectask',
            name='exec_status',
            field=models.CharField(choices=[('0', '待批准'), ('1', '未批准'), ('2', '已批准'), ('3', '处理中'), ('4', '已完成'), ('5', '已关闭')], default='0', max_length=10, verbose_name='执行进度'),
        ),
        migrations.AlterField(
            model_name='incepmakeexectask',
            name='sqlsha1',
            field=models.CharField(default='', max_length=120, verbose_name='sqlsha1'),
        ),
    ]
