# Generated by Django 2.0.2 on 2018-03-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0023_auto_20180308_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='incepmakeexectask',
            name='backup_dbname',
            field=models.CharField(default='', max_length=1024, verbose_name='inception生成的备份的库名'),
        ),
        migrations.AddField(
            model_name='incepmakeexectask',
            name='exec_log',
            field=models.TextField(default='', verbose_name='执行成功的记录'),
        ),
        migrations.AddField(
            model_name='incepmakeexectask',
            name='sequence',
            field=models.CharField(default='', max_length=1024, verbose_name='备份记录id，inception生成的sequence'),
        ),
    ]
