# Generated by Django 2.0.2 on 2018-03-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0025_auto_20180313_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inceptionhostconfig',
            options={'default_permissions': (), 'verbose_name': 'Inception账号配置', 'verbose_name_plural': 'Inception账号配置'},
        ),
        migrations.AlterModelOptions(
            name='remark',
            options={'default_permissions': (), 'verbose_name': '线上审核备注表', 'verbose_name_plural': '线上审核备注表'},
        ),
    ]
