# Generated by Django 2.0.2 on 2018-03-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0026_auto_20180321_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inceptionhostconfig',
            options={'default_permissions': (), 'verbose_name': '数据库连接账号', 'verbose_name_plural': '数据库连接账号'},
        ),
        migrations.AlterModelOptions(
            name='remark',
            options={'default_permissions': (), 'verbose_name': '线上操作备注', 'verbose_name_plural': '线上操作备注'},
        ),
    ]
