# Generated by Django 2.0.2 on 2018-03-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0028_auto_20180322_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incepmakeexectask',
            name='exec_status',
            field=models.CharField(choices=[('0', '未执行'), ('1', '已完成'), ('2', '处理中'), ('3', '回滚中'), ('4', '已回滚')], default='0', max_length=10, verbose_name='执行进度'),
        ),
    ]
