# Generated by Django 2.0.2 on 2018-03-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0029_auto_20180322_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='incepmakeexectask',
            name='rollback_sqlsha1',
            field=models.CharField(default='', max_length=120, verbose_name='sqlsha1'),
        ),
    ]
