# Generated by Django 2.0.2 on 2018-03-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0030_incepmakeexectask_rollback_sqlsha1'),
    ]

    operations = [
        migrations.AddField(
            model_name='incepmakeexectask',
            name='category',
            field=models.CharField(choices=[('0', '线下任务'), ('1', '线上任务')], default='0', max_length=2, verbose_name='线上还是线下任务'),
        ),
    ]
