# Generated by Django 2.0.2 on 2018-03-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0031_incepmakeexectask_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineauditcontents',
            name='type',
            field=models.CharField(choices=[('DDL', '数据库定义语言'), ('DML', '数据库操纵语言')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='incepmakeexectask',
            name='category',
            field=models.CharField(choices=[('0', '线下任务'), ('1', '线上任务')], default='0', max_length=2, verbose_name='任务分类'),
        ),
    ]
