# Generated by Django 2.0.2 on 2018-03-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0032_auto_20180323_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineauditcontents',
            name='taskid',
            field=models.CharField(default='', max_length=128, verbose_name='任务号'),
        ),
    ]
