# Generated by Django 2.0.2 on 2018-03-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0033_onlineauditcontents_taskid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineauditcontents',
            name='taskid',
        ),
        migrations.AddField(
            model_name='incepmakeexectask',
            name='related_id',
            field=models.IntegerField(default=0, verbose_name='关联OnlineAuditContents的主键id'),
        ),
    ]
