# Generated by Django 2.0.2 on 2018-03-23 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0013_delete_ldapuser'),
        ('ProjectManager', '0034_auto_20180323_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='incepmakeexectask',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserManager.Groups', verbose_name='项目组id'),
            preserve_default=False,
        ),
    ]
