# Generated by Django 2.0.2 on 2018-04-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLockRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('thread', models.IntegerField()),
                ('txn_time', models.SmallIntegerField()),
                ('user', models.CharField(max_length=16)),
                ('ip', models.CharField(max_length=15)),
                ('db', models.CharField(max_length=64)),
                ('tbl', models.CharField(max_length=64)),
                ('idx', models.CharField(max_length=64)),
                ('lock_type', models.CharField(max_length=16)),
                ('lock_mode', models.CharField(max_length=1)),
                ('wait_hold', models.CharField(max_length=1)),
                ('victim', models.SmallIntegerField()),
                ('query', models.TextField()),
                ('is_sign', models.CharField(choices=[('0', '未推送'), ('1', '已推送')], default='0', max_length=1)),
                ('src_host', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name': '记录死锁表',
                'verbose_name_plural': '记录死锁表',
                'db_table': 'dbaudit_deadlocks_records',
                'permissions': (),
            },
        ),
    ]
