# Generated by Django 2.2.20 on 2022-08-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconfig',
            name='rds_category',
            field=models.SmallIntegerField(choices=[(1, 'mysql'), (2, 'tidb'), (3, 'clickhouse')], default=1, verbose_name='数据库类别'),
        ),
        migrations.AlterField(
            model_name='dborders',
            name='rds_category',
            field=models.SmallIntegerField(choices=[(1, 'mysql'), (2, 'tidb'), (3, 'clickhouse')], default=1, verbose_name='数据库类别'),
        ),
    ]
