# Generated by Django 2.2.20 on 2022-09-01 07:29

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0002_auto_20220826_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbconfig',
            name='custom_audit_parameters',
            field=django_jsonfield_backport.models.JSONField(blank=True, default=dict, null=True, verbose_name='自定义审核参数'),
        ),
    ]
